### ISSUE TITLE
Bug in the search page

### ISSUE THREAD

**Issue by Apocalixs-Nick** [Lucos18/EasyCarNew#5]
In the search fragment I encountered the following problem:
Putting the minimum and maximum value in the text and power section, putting 0 before the maximum values, the search still works; also at some vehicle types that are obtained from the search some logos overlap with the vehicle model

![bug-search](https://user-images.githubusercontent.com/110109361/208898684-9d80a4d8-792f-42a8-9e04-21552bb59e4b.gif)

**Comment by Lucos18** [comment]
This is an intended feature, because if a user add 0 as the first digit to the search, in maximum text input, the 0s aren't counted because the maximum values can't be 0 or minor than that.
